# Generated by Django 6.0 on 2026-01-08 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_is_approved_userprofile_favoriteteam_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('roster_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'ожидает'), ('approved', 'одобрена'), ('rejected', 'отклонена')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_applications', to='core.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tournament', 'status'], name='core_teamap_tournam_2b4f3a_idx'), models.Index(fields=['user', 'created_at'], name='core_teamap_user_id_dfc25a_idx')],
            },
        ),
    ]
