# Generated by Django 6.0 on 2026-01-09 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teamapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, default='', max_length=80)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('roster', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'ожидает'), ('approved', 'одобрено'), ('rejected', 'отклонено')], default='pending', max_length=20)),
                ('admin_comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to='core.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tournament', 'status', 'created_at'], name='core_teamre_tournam_d32f56_idx'), models.Index(fields=['user', 'created_at'], name='core_teamre_user_id_6ffec4_idx')],
            },
        ),
    ]
